import { Request, Response } from 'express';
import Report from '../models/Report';
import Project from '../models/Project';
import Event from '../models/Event';
import User from '../models/User';
import { AuthRequest } from '../middlewares/auth.middleware';
import { generateMonthlyReportSchema, paginationSchema } from '../validation/schemas';
import { z } from 'zod';

export const generateMonthlyReport = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { month, year } = generateMonthlyReportSchema.parse(req.body);
    const period = `${month}/${year}`;

    // Calculate dates
    const startDate = new Date(year, month - 1, 1);
    const endDate = new Date(year, month, 0, 23, 59, 59);

    // Fetch data
    const projects = await Project.find({
      createdAt: { $gte: startDate, $lte: endDate }
    });

    const events = await Event.find({
      startTime: { $gte: startDate, $lte: endDate }
    });

    const activeMembers = await User.countDocuments({ 
      status: 'active',
      createdAt: { $lte: endDate } 
    });

    // Compute basic stats
    const totalProjects = projects.length;
    const approvedProjects = projects.filter(p => p.status === 'approved').length;
    const completedProjects = projects.filter(p => p.status === 'completed').length;
    
    // Financials
    const totalEstimatedBudget = projects.reduce((acc, p) => acc + (p.budget?.estimated || 0), 0);
    const totalActualSpent = projects.reduce((acc, p) => acc + (p.budget?.actual || 0), 0);

    const totalEvents = events.length;

    const projectHighlights = projects.map(p => ({ title: p.title, status: p.status, avenue: p.avenue }));
    const eventHighlights = events.map(e => ({ title: e.title, type: e.type, date: e.startTime }));

    // Generate Markdown representation
    const markdown = `
# Rotaract Club of SLIIT - Monthly Summary Report
**Period:** ${month}/${year}

## 📊 Overview
- **Active Members:** ${activeMembers}
- **Total Events Hosted:** ${totalEvents}
- **New Projects Initiated:** ${totalProjects}
  - Approved: ${approvedProjects}
  - Completed: ${completedProjects}

## 💰 Financial Summary
- **Estimated Budget (New Projects):** LKR ${totalEstimatedBudget.toLocaleString()}
- **Actual Spent:** LKR ${totalActualSpent.toLocaleString()}

## 📅 Events Hosted This Month
${events.length === 0 ? '*No events hosted this month.*' : events.map(e => `- **${e.title}** (${new Date(e.startTime).toLocaleDateString()}) - ${e.type}`).join('\n')}

## 🚀 Project Highlights
${projects.length === 0 ? '*No projects initiated this month.*' : projects.map(p => `- **${p.title}** [${p.avenue}] - Status: ${p.status}`).join('\n')}

---
*Report auto-generated by the Rotaract SLIIT Portal System*
    `.trim();

    const reportData = {
      totalProjects,
      approvedProjects,
      completedProjects,
      totalEvents,
      activeMembers,
      totalEstimatedBudget,
      totalActualSpent,
      projectHighlights,
      eventHighlights,
      markdown
    };

    const report = await Report.create({
      title: `Monthly Summary: ${period}`,
      type: 'monthly_summary',
      period,
      generatedData: reportData,
      generatedBy: req.user?._id
    });

    res.status(201).json(report);
  } catch (error) {
    if (error instanceof z.ZodError) {
      res.status(400).json({ message: 'Validation error', errors: error.issues });
    } else {
      res.status(500).json({ message: 'Server error', error: (error as Error).message });
    }
  }
};

export const getReports = async (req: Request, res: Response): Promise<void> => {
  try {
    const { page, limit } = paginationSchema.parse(req.query);
    const skip = (page - 1) * limit;

    const reports = await Report.find()
      .select('-generatedData.markdown -generatedData.projectHighlights -generatedData.eventHighlights')
      .sort({ createdAt: -1 })
      .populate('generatedBy', 'firstName lastName')
      .skip(skip)
      .limit(limit);

    const total = await Report.countDocuments();

    res.json({
      data: reports,
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit)
      }
    });
  } catch (error) {
    if (error instanceof z.ZodError) {
      res.status(400).json({ message: 'Validation error', errors: error.issues });
    } else {
      res.status(500).json({ message: 'Server error', error: (error as Error).message });
    }
  }
};

export const getReportById = async (req: Request, res: Response): Promise<void> => {
  try {
    const report = await Report.findById(req.params.id).populate('generatedBy', 'firstName lastName');
    if (!report) {
      res.status(404).json({ message: 'Report not found' });
      return;
    }
    res.json(report);
  } catch (error) {
    res.status(500).json({ message: 'Server error', error: (error as Error).message });
  }
};
