import { Request, Response } from 'express';
import Report from '../models/Report';
import Project from '../models/Project';
import Event from '../models/Event';
import User from '../models/User';
import AttendanceRecord from '../models/AttendanceRecord';
import { AuthRequest } from '../middlewares/auth.middleware';
import {
  generateMonthlyReportSchema,
  generateServiceHoursReportSchema,
  generateMembershipReportSchema,
  generateFinancialReportSchema,
  paginationSchema,
} from '../validation/schemas';
import { z } from 'zod';

export const generateMonthlyReport = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { month, year } = generateMonthlyReportSchema.parse(req.body);
    const period = `${month}/${year}`;

    // Calculate dates
    const startDate = new Date(year, month - 1, 1);
    const endDate = new Date(year, month, 0, 23, 59, 59);

    // Fetch data
    const projects = await Project.find({
      createdAt: { $gte: startDate, $lte: endDate }
    });

    const events = await Event.find({
      startTime: { $gte: startDate, $lte: endDate }
    });

    const activeMembers = await User.countDocuments({ 
      status: 'active',
      createdAt: { $lte: endDate } 
    });

    // Compute basic stats
    const totalProjects = projects.length;
    const approvedProjects = projects.filter(p => p.status === 'approved').length;
    const completedProjects = projects.filter(p => p.status === 'completed').length;
    
    // Financials
    const totalEstimatedBudget = projects.reduce((acc, p) => acc + (p.budget?.estimated || 0), 0);
    const totalActualSpent = projects.reduce((acc, p) => acc + (p.budget?.actual || 0), 0);

    const totalEvents = events.length;

    const projectHighlights = projects.map(p => ({ title: p.title, status: p.status, avenue: p.avenue }));
    const eventHighlights = events.map(e => ({ title: e.title, type: e.type, date: e.startTime }));

    // Generate Markdown representation
    const markdown = `
# Rotaract Club of SLIIT - Monthly Summary Report
**Period:** ${month}/${year}

## 📊 Overview
- **Active Members:** ${activeMembers}
- **Total Events Hosted:** ${totalEvents}
- **New Projects Initiated:** ${totalProjects}
  - Approved: ${approvedProjects}
  - Completed: ${completedProjects}

## 💰 Financial Summary
- **Estimated Budget (New Projects):** LKR ${totalEstimatedBudget.toLocaleString()}
- **Actual Spent:** LKR ${totalActualSpent.toLocaleString()}

## 📅 Events Hosted This Month
${events.length === 0 ? '*No events hosted this month.*' : events.map(e => `- **${e.title}** (${new Date(e.startTime).toLocaleDateString()}) - ${e.type}`).join('\n')}

## 🚀 Project Highlights
${projects.length === 0 ? '*No projects initiated this month.*' : projects.map(p => `- **${p.title}** [${p.avenue}] - Status: ${p.status}`).join('\n')}

---
*Report auto-generated by the Rotaract SLIIT Portal System*
    `.trim();

    const reportData = {
      totalProjects,
      approvedProjects,
      completedProjects,
      totalEvents,
      activeMembers,
      totalEstimatedBudget,
      totalActualSpent,
      projectHighlights,
      eventHighlights,
      markdown
    };

    const report = await Report.create({
      title: `Monthly Summary: ${period}`,
      type: 'monthly_summary',
      period,
      generatedData: reportData,
      generatedBy: req.user?._id
    });

    res.status(201).json(report);
  } catch (error) {
    if (error instanceof z.ZodError) {
      res.status(400).json({ message: 'Validation error', errors: error.issues });
    } else {
      res.status(500).json({ message: 'Server error', error: (error as Error).message });
    }
  }
};

// Service hours per member: sums (event.endTime - event.startTime) for every event
// a member checked into (via AttendanceRecord) that started within the given month.
export const generateServiceHoursReport = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { month, year } = generateServiceHoursReportSchema.parse(req.body);
    const period = `${month}/${year}`;
    const startDate = new Date(year, month - 1, 1);
    const endDate = new Date(year, month, 0, 23, 59, 59);

    const events = await Event.find({ startTime: { $gte: startDate, $lte: endDate } }).select('startTime endTime');
    const eventIds = events.map((e) => e._id);
    const durationHoursByEvent = new Map(
      events.map((e) => [e._id.toString(), (e.endTime.getTime() - e.startTime.getTime()) / (1000 * 60 * 60)])
    );

    const records = await AttendanceRecord.find({ eventId: { $in: eventIds } })
      .populate('userId', 'firstName lastName sliitIndex avenue');

    const hoursByUser = new Map<string, { user: any; hours: number; eventsAttended: number }>();
    for (const record of records) {
      const user: any = record.userId;
      if (!user) continue;
      const key = user._id.toString();
      const duration = durationHoursByEvent.get(record.eventId.toString()) || 0;
      const existing = hoursByUser.get(key) || { user, hours: 0, eventsAttended: 0 };
      existing.hours += duration;
      existing.eventsAttended += 1;
      hoursByUser.set(key, existing);
    }

    const memberHours = Array.from(hoursByUser.values())
      .map((m) => ({ user: m.user, hours: Math.round(m.hours * 100) / 100, eventsAttended: m.eventsAttended }))
      .sort((a, b) => b.hours - a.hours);

    const totalServiceHours = Math.round(memberHours.reduce((acc, m) => acc + m.hours, 0) * 100) / 100;

    const markdown = `
# Rotaract Club of SLIIT - Service Hours Report
**Period:** ${month}/${year}

## Summary
- **Total Service Hours (Club-wide):** ${totalServiceHours}
- **Members with Recorded Hours:** ${memberHours.length}

## Member Breakdown
${memberHours.length === 0 ? '*No attendance recorded this period.*' : memberHours.map(m => `- **${m.user.firstName} ${m.user.lastName}** (${m.user.sliitIndex || 'N/A'}) — ${m.hours} hrs across ${m.eventsAttended} event(s)`).join('\n')}

---
*Report auto-generated by the Rotaract SLIIT Portal System*
    `.trim();

    const reportData = { totalServiceHours, memberHours, markdown };

    const report = await Report.create({
      title: `Service Hours Report: ${period}`,
      type: 'service_hours',
      period,
      generatedData: reportData,
      generatedBy: req.user?._id
    });

    res.status(201).json(report);
  } catch (error) {
    if (error instanceof z.ZodError) {
      res.status(400).json({ message: 'Validation error', errors: error.issues });
    } else {
      res.status(500).json({ message: 'Server error', error: (error as Error).message });
    }
  }
};

// Membership counts by status/avenue/batch year, plus a join-date trend by month.
export const generateMembershipReport = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { month, year } = generateMembershipReportSchema.parse(req.body);
    const period = `${month}/${year}`;
    const endDate = new Date(year, month, 0, 23, 59, 59);

    const users = await User.find({ createdAt: { $lte: endDate } }).select('status avenue batchYear joinDate createdAt');

    const byStatus: Record<string, number> = {};
    const byAvenue: Record<string, number> = {};
    const byBatchYear: Record<string, number> = {};
    const joinTrend: Record<string, number> = {};

    for (const u of users) {
      byStatus[u.status] = (byStatus[u.status] || 0) + 1;
      if (u.avenue) byAvenue[u.avenue] = (byAvenue[u.avenue] || 0) + 1;
      byBatchYear[String(u.batchYear)] = (byBatchYear[String(u.batchYear)] || 0) + 1;
      const joinDate = u.joinDate || (u as any).createdAt;
      const key = `${joinDate.getFullYear()}-${String(joinDate.getMonth() + 1).padStart(2, '0')}`;
      joinTrend[key] = (joinTrend[key] || 0) + 1;
    }

    const totalMembers = users.length;
    const activeMembers = byStatus['active'] || 0;

    const markdown = `
# Rotaract Club of SLIIT - Membership Report
**As of:** ${month}/${year}

## Summary
- **Total Members (all-time):** ${totalMembers}
- **Active Members:** ${activeMembers}

## By Status
${Object.entries(byStatus).map(([k, v]) => `- ${k}: ${v}`).join('\n')}

## By Avenue
${Object.entries(byAvenue).length === 0 ? '*No avenue data.*' : Object.entries(byAvenue).map(([k, v]) => `- ${k}: ${v}`).join('\n')}

## By Batch Year
${Object.entries(byBatchYear).sort().map(([k, v]) => `- ${k}: ${v}`).join('\n')}

## Join Date Trend (by month)
${Object.entries(joinTrend).sort().map(([k, v]) => `- ${k}: ${v} new member(s)`).join('\n')}

---
*Report auto-generated by the Rotaract SLIIT Portal System*
    `.trim();

    const reportData = { totalMembers, activeMembers, byStatus, byAvenue, byBatchYear, joinTrend, markdown };

    const report = await Report.create({
      title: `Membership Report: ${period}`,
      type: 'membership',
      period,
      generatedData: reportData,
      generatedBy: req.user?._id
    });

    res.status(201).json(report);
  } catch (error) {
    if (error instanceof z.ZodError) {
      res.status(400).json({ message: 'Validation error', errors: error.issues });
    } else {
      res.status(500).json({ message: 'Server error', error: (error as Error).message });
    }
  }
};

// Budget totals grouped by avenue, for projects created within the given month.
export const generateFinancialReport = async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { month, year } = generateFinancialReportSchema.parse(req.body);
    const period = `${month}/${year}`;
    const startDate = new Date(year, month - 1, 1);
    const endDate = new Date(year, month, 0, 23, 59, 59);

    const projects = await Project.find({ createdAt: { $gte: startDate, $lte: endDate } }).select('title avenue budget status');

    const byAvenue: Record<string, { estimated: number; actual: number; projectCount: number }> = {};
    for (const p of projects) {
      const key = p.avenue;
      if (!byAvenue[key]) byAvenue[key] = { estimated: 0, actual: 0, projectCount: 0 };
      byAvenue[key].estimated += p.budget?.estimated || 0;
      byAvenue[key].actual += p.budget?.actual || 0;
      byAvenue[key].projectCount += 1;
    }

    const totalEstimated = Object.values(byAvenue).reduce((acc, a) => acc + a.estimated, 0);
    const totalActual = Object.values(byAvenue).reduce((acc, a) => acc + a.actual, 0);

    const markdown = `
# Rotaract Club of SLIIT - Financial Summary by Avenue
**Period:** ${month}/${year}

## Club-wide Totals
- **Total Estimated Budget:** LKR ${totalEstimated.toLocaleString()}
- **Total Actual Spent:** LKR ${totalActual.toLocaleString()}

## By Avenue
${Object.entries(byAvenue).length === 0 ? '*No projects with budgets this period.*' : Object.entries(byAvenue).map(([avenue, a]) => `- **${avenue}** (${a.projectCount} project(s)) — Estimated: LKR ${a.estimated.toLocaleString()}, Actual: LKR ${a.actual.toLocaleString()}`).join('\n')}

---
*Report auto-generated by the Rotaract SLIIT Portal System*
    `.trim();

    const reportData = { totalEstimated, totalActual, byAvenue, markdown };

    const report = await Report.create({
      title: `Financial Summary by Avenue: ${period}`,
      type: 'financial_per_avenue',
      period,
      generatedData: reportData,
      generatedBy: req.user?._id
    });

    res.status(201).json(report);
  } catch (error) {
    if (error instanceof z.ZodError) {
      res.status(400).json({ message: 'Validation error', errors: error.issues });
    } else {
      res.status(500).json({ message: 'Server error', error: (error as Error).message });
    }
  }
};

export const getReports = async (req: Request, res: Response): Promise<void> => {
  try {
    const { page, limit } = paginationSchema.parse(req.query);
    const skip = (page - 1) * limit;

    const [reports, total] = await Promise.all([
      Report.find()
        .sort({ createdAt: -1 })
        .populate('generatedBy', 'firstName lastName')
        .skip(skip)
        .limit(limit)
        .lean(),
      Report.countDocuments(),
    ]);

    // .select() doesn't reliably strip nested keys inside a Schema.Types.Mixed
    // field, so trim the heavy markdown/highlight payloads manually for the list view.
    const trimmed = reports.map((r) => {
      const generatedData: any = r.generatedData || {};
      const { markdown, projectHighlights, eventHighlights, memberHours, byAvenue, byStatus, byBatchYear, joinTrend, ...rest } = generatedData;
      return { ...r, generatedData: rest };
    });

    res.json({
      data: trimmed,
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit)
      }
    });
  } catch (error) {
    if (error instanceof z.ZodError) {
      res.status(400).json({ message: 'Validation error', errors: error.issues });
    } else {
      res.status(500).json({ message: 'Server error', error: (error as Error).message });
    }
  }
};

export const getReportById = async (req: Request, res: Response): Promise<void> => {
  try {
    const report = await Report.findById(req.params.id).populate('generatedBy', 'firstName lastName');
    if (!report) {
      res.status(404).json({ message: 'Report not found' });
      return;
    }
    res.json(report);
  } catch (error) {
    res.status(500).json({ message: 'Server error', error: (error as Error).message });
  }
};
